### ISSUE TITLE
generate json files for other build/editor tools.

### ISSUE THREAD

**Issue by davidmlw** [sifive/api-scala-sifive#30]
generate a `.bloop` directory in WORKSPACE, including all the json files in build/api-scala-sifive/bloop/, with the only difference being the `out` and `classesDir` in .bloop/module-name too.

I will try to file a PR lately

**Comment by davidmlw** [comment]
https://github.com/sifive/api-scala-sifive/blob/3211bbe9ef541af972a9a3cefaf21b3882461439/scala.wake#L366

Why we don't just use bloop server and bloop client?

**Comment by jackkoenig** [comment]
The problem with using the Bloop server is that it uses unauthenticated TCP ports (defaulting to the same one, 8212) which is insecure on multi-user systems. I originally had it using the server, but had to back it out because my invocations of api-scala-sifive were compiling code as my coworker via his bloop server.

There is an open issue on Bloop to make it work with named pipes on Windows (it already works or mostly works on Mac and Linux) https://github.com/scalacenter/bloop/issues/281 that I have been hoping to get to and fix so that we can use Bloop servers via named pipes, but I just haven't had time.
